# Generated by Django 3.1.5 on 2021-03-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id_meet', models.IntegerField(primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('round', models.IntegerField()),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.player')),
                ('id_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.player')),
            ],
        ),
    ]
