# Generated by Django 3.1.5 on 2021-03-17 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotkania', '0002_auto_20210317_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='result',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
