# Generated by Django 2.2b1 on 2021-03-22 18:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('country', models.CharField(blank=True, max_length=60)),
                ('club', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 22, 19, 38, 9, 843698), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 3, 22, 18, 38, 9, 844695, tzinfo=utc))])),
                ('Maxparticipants', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('mincategory', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('maxcategory', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0)])),
                ('gamesystem', models.CharField(choices=[('RR', 'round-robin'), ('LABEL', 'label')], default='RR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id_meet', models.IntegerField(primary_key=True, serialize=False)),
                ('result', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('date', models.DateTimeField()),
                ('round', models.IntegerField()),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.Player')),
                ('id_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.Player')),
            ],
        ),
    ]
