# Generated by Django 3.1.7 on 2021-04-07 14:36

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='drawpoints',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='losepoints',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pairingsystem',
            field=models.CharField(choices=[('random', 'random'), ('netherland', 'netherland'), ('monrad', 'monrad')], default='RANDOM', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winpoints',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 7, 16, 36, 38, 348424), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 4, 7, 14, 36, 38, 348423, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='playtype',
            field=models.CharField(choices=[('RR', 'round-robin'), ('LABEL', 'label'), ('groups', 'groups')], default='RR', max_length=20),
        ),
    ]
