# Generated by Django 3.1.7 on 2021-04-07 14:38

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210407_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='memberslimit',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 7, 16, 38, 45, 527026), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 4, 7, 14, 38, 45, 527026, tzinfo=utc))]),
        ),
    ]
