# Generated by Django 3.1.7 on 2021-03-21 21:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210321_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='time',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 21, 22, 24, 22, 983687), validators=[django.core.validators.MinValueValidator(datetime.date(2021, 3, 21))]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mincategory',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
