# Generated by Django 3.1.7 on 2021-04-07 16:05

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210407_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='byepoints',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 7, 18, 5, 43, 37815), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 4, 7, 16, 5, 43, 37815, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='drawpoints',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='losepoints',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winpoints',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
