# Generated by Django 3.1.7 on 2021-03-21 21:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20210321_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 21, 22, 47, 19, 766875), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 3, 21, 21, 47, 19, 766874, tzinfo=utc))]),
        ),
    ]
