# Generated by Django 3.1.7 on 2021-04-07 16:16

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20210407_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('RR', 'round-robin'), ('LABEL', 'label'), ('groups', 'groups')], default='mixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 7, 18, 16, 49, 942897), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 4, 7, 16, 16, 49, 942896, tzinfo=utc))]),
        ),
    ]
