# Generated by Django 3.1.7 on 2021-04-07 16:17

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20210407_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 7, 18, 17, 34, 208927), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 4, 7, 16, 17, 34, 208926, tzinfo=utc))]),
        ),
    ]
