# Generated by Django 3.1.7 on 2021-03-21 21:50

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20210321_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gamesystem',
            field=models.CharField(choices=[('rr', 'każdy-z-każdym'), ('label', 'drabinka')], default='RR', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 21, 22, 50, 32, 724177), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 3, 21, 21, 50, 32, 724177, tzinfo=utc))]),
        ),
    ]
