# Generated by Django 3.1.7 on 2021-03-21 21:56

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_auto_20210321_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.AddField(
            model_name='tournament',
            name='Maxparticipants',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 21, 22, 56, 12, 286608), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 3, 21, 21, 56, 12, 286607, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mincategory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
