# Generated by Django 3.1.7 on 2021-03-21 22:12

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20210321_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='Maxparticipants',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 21, 23, 12, 52, 662490), validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 3, 21, 22, 12, 52, 662489, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='gamesystem',
            field=models.CharField(choices=[('RR', 'każdy-z-każdym'), ('LABEL', 'drabinka')], default='RR', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='maxcategory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mincategory',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
